<a href="https://colab.research.google.com/github/Feznix/Stats-554/blob/Homework-5/Homework6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Name: Heather Secrest

Date: 05/11/2026

Course: ST 554 (601)

Homework 6

In [11]:
#bring in the module
import sqlite3
import pandas as pd
import numpy as np
#make the connection to the file. My file is in the main folder on the left
MLB = sqlite3.connect("lahman_1871-2022.sqlite")

In [6]:
#use the pd.read_sql() to return a dataframe
# SQL selects all columns from the schema where the type is a table
pd.read_sql('SELECT * FROM sqlite_schema \
            WHERE type = "table"',MLB)

,type,name,tbl_name,rootpage,sql
0,table,AllstarFull,AllstarFull,2,"CREATE TABLE AllstarFull (\nplayerID TEXT,\nye..."
1,table,Appearances,Appearances,3,"CREATE TABLE Appearances (\nyearID INTEGER,\nt..."
2,table,AwardsManagers,AwardsManagers,4,"CREATE TABLE AwardsManagers (\nplayerID TEXT,\..."
3,table,AwardsPlayers,AwardsPlayers,5,"CREATE TABLE AwardsPlayers (\nplayerID TEXT,\n..."
4,table,AwardsShareManagers,AwardsShareManagers,6,CREATE TABLE AwardsShareManagers (\nawardID TE...
5,table,AwardsSharePlayers,AwardsSharePlayers,7,CREATE TABLE AwardsSharePlayers (\nawardID TEX...
6,table,Batting,Batting,8,"CREATE TABLE Batting (\nplayerID TEXT,\nyearID..."
7,table,BattingPost,BattingPost,9,"CREATE TABLE BattingPost (\nyearID INTEGER,\nr..."
8,table,CollegePlaying,CollegePlaying,10,"CREATE TABLE CollegePlaying (\nplayerID TEXT,\..."
9,table,Fielding,Fielding,11,"CREATE TABLE Fielding (\nplayerID TEXT,\nyearI..."
10,table,FieldingOF,FieldingOF,12,"CREATE TABLE FieldingOF (\nplayerID TEXT,\nyea..."
11,table,FieldingOFsplit,FieldingOFsplit,13,"CREATE TABLE FieldingOFsplit (\nplayerID TEXT,..."
12,table,FieldingPost,FieldingPost,14,"CREATE TABLE FieldingPost (\nplayerID TEXT,\ny..."
13,table,HallOfFame,HallOfFame,15,"CREATE TABLE HallOfFame (\nplayerID TEXT,\nyea..."
14,table,HomeGames,HomeGames,16,"CREATE TABLE HomeGames (\nyearkey INTEGER,\nle..."
15,table,Managers,Managers,17,"CREATE TABLE Managers (\nplayerID TEXT,\nyearI..."
16,table,ManagersHalf,ManagersHalf,18,"CREATE TABLE ManagersHalf (\nplayerID TEXT,\ny..."
17,table,Parks,Parks,19,"CREATE TABLE Parks (\nID INTEGER,\nparkalias T..."
18,table,People,People,21,"CREATE TABLE People (\nID INTEGER,\nplayerID T..."
19,table,Pitching,Pitching,23,"CREATE TABLE Pitching (\nplayerID TEXT,\nyearI..."
20,table,PitchingPost,PitchingPost,24,"CREATE TABLE PitchingPost (\nplayerID TEXT,\ny..."
21,table,Salaries,Salaries,25,"CREATE TABLE Salaries (\nyearID INTEGER,\nteam..."
22,table,Schools,Schools,26,"CREATE TABLE Schools (\nschoolID TEXT,\nname_f..."
23,table,SeriesPost,SeriesPost,27,"CREATE TABLE SeriesPost (\nyearID INTEGER,\nro..."
24,table,Teams,Teams,28,"CREATE TABLE Teams (\nyearID INTEGER,\nlgID TE..."
25,table,TeamsFranchises,TeamsFranchises,29,"CREATE TABLE TeamsFranchises (\nfranchID TEXT,..."
26,table,TeamsHalf,TeamsHalf,30,"CREATE TABLE TeamsHalf (\nyearID INTEGER,\nlgI..."

In [9]:
def execute_query(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        print("Query executed successfully")
    except Error as e:
        print(f"The error '{e}' occurred")
    cursor.close()

In [46]:
#create a 'cursor' object from our connection
cursor = MLB.cursor()

#SQL query to create a new table in the data base

new_table = """
          CREATE TABLE IF NOT EXISTS HallofFamePitchers(
          playerID TEXT,
          Total_GS REAL,
          Total_G REAL,
          Total_W REAL,
          Total_L REAL,
          IPOuts REAL,
          Total_CG REAL,
          Total_SHO REAL,
          Total_SV REAL)
        """

#execute the SQL query on the database!
cursor.execute(new_table)

#The information for the query is stored in memory. We use the fetchall() method to actually return the information
result = cursor.fetchall()

#finall we close the connection the cursor made with that query
cursor.close()

In [48]:
#create a 'cursor' object from our connection
cursor = MLB.cursor()

#SQL query to create a new table in the data base

insert_data = """
              INSERT INTO HallofFamePitchers(playerID,
               Total_GS, Total_G,
               Total_W, Total_L,
               IPOuts, Total_CG,
               Total_SHO, Total_SV)
              SELECT h.playerID,
              SUM(p.GS), SUM(p.G),
              SUM(p.W), SUM(p.L),
              SUM(p.IPouts), SUM(p.CG),
              SUM(p.SHO), SUM(p.SV)
              FROM HallofFame AS h
              INNER JOIN Pitching AS p
              ON h.playerID = p.playerID
              GROUP BY h.playerID"""

#execute the SQL query on the database!
cursor.executescript(insert_data)

#The information for the query is stored in memory. We use the fetchall() method to actually return the information
result = cursor.fetchall()

#finall we close the connection the cursor made with that query
cursor.close()

In [44]:
#create a 'cursor' object from our connection
cursor = MLB.cursor()

#SQL query to create a new table in the data base

drop_table = """ DROP TABLE HallofFamePitchers;
        """

#execute the SQL query on the database!
cursor.execute(drop_table)

#The information for the query is stored in memory. We use the fetchall() method to actually return the information
result = cursor.fetchall()

#finall we close the connection the cursor made with that query
cursor.close()

In [49]:
pd.read_sql('''SELECT *
              FROM HallofFamePitchers''',MLB)

,playerID,Total_GS,Total_G,Total_W,Total_L,IPOuts,Total_CG,Total_SHO,Total_SV
0,abbotji01,254.0,263.0,87.0,108.0,5022.0,31.0,6.0,0.0
1,adamsba01,5325.0,7230.0,2910.0,2100.0,134790.0,3090.0,660.0,225.0
2,aguilri01,89.0,732.0,86.0,81.0,3874.0,10.0,0.0,318.0
3,akerja01,0.0,495.0,47.0,45.0,2238.0,0.0,0.0,123.0
4,alexado01,464.0,561.0,194.0,174.0,10103.0,98.0,18.0,3.0
...,...,...,...,...,...,...,...,...,...
522,zachrpa01,154.0,293.0,69.0,67.0,3532.0,29.0,7.0,3.0
523,zahnge01,270.0,304.0,111.0,109.0,5547.0,79.0,20.0,1.0
524,zambrca01,302.0,354.0,132.0,91.0,5877.0,10.0,5.0,0.0
525,zeileto01,0.0,2.0,0.0,0.0,6.0,0.0,0.0,0.0
526,zitoba01,421.0,433.0,165.0,143.0,7730.0,12.0,5.0,0.0

In [39]:
pd.read_sql( '''SELECT h.playerID,
              SUM(p.GS), SUM(p.G),
              SUM(p.W), SUM(p.L),
              SUM(p.IPouts), SUM(p.CG),
              SUM(p.SHO), SUM(p.SV)
              FROM HallofFame AS h
              INNER JOIN Pitching AS p
              ON h.playerID = p.playerID
              GROUP BY h.playerID''',MLB)

,playerID,SUM(p.GS),SUM(p.G),SUM(p.W),SUM(p.L),SUM(p.IPouts),SUM(p.CG),SUM(p.SHO),SUM(p.SV)
0,abbotji01,254,263,87,108,5022,31,6,0
1,adamsba01,5325,7230,2910,2100,134790,3090,660,225
2,aguilri01,89,732,86,81,3874,10,0,318
3,akerja01,0,495,47,45,2238,0,0,123
4,alexado01,464,561,194,174,10103,98,18,3
...,...,...,...,...,...,...,...,...,...
522,zachrpa01,154,293,69,67,3532,29,7,3
523,zahnge01,270,304,111,109,5547,79,20,1
524,zambrca01,302,354,132,91,5877,10,5,0
525,zeileto01,0,2,0,0,6,0,0,0
526,zitoba01,421,433,165,143,7730,12,5,0